buildscript {
    ext {
        shadowJarVersion = '7.1.2'
        graalvmNativeImageVersion = '0.10.5'
    }
}

plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version "${shadowJarVersion}"
    id 'org.graalvm.buildtools.native' version "${graalvmNativeImageVersion}"
    id 'checkstyle'
}

group = 'ddns.cli'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

shadowJar {
    archiveBaseName.set('ddns-cli-all')
    archiveVersion.set('1.0.0')
    manifest {
        attributes 'Main-Class': 'ddns.cli.App'
    }
}

graalvmNative {
    binaries {
        main {
            imageName = 'application'
            mainClass = 'ddns.cli.App'
            verbose = true
            useFatJar = true
            debug = false
            sharedLibrary = false
            quickBuild = false
            richOutput = false
            buildArgs.add('-O1')
            buildArgs.add('-march=native')
            buildArgs.add('--initialize-at-build-time')
            buildArgs.add('--enable-url-protocols=http')
            buildArgs.add('--no-server')
            buildArgs.add('--no-fallback')
            javaLauncher = javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(17)
                vendor = JvmVendorSpec.matching("Oracle Corporation")
            }
        }
    }
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'checkstyle'

    java {
        sourceCompatibility = JavaVersion.VERSION_17
    }

    checkstyle {
        toolVersion = "10.12.4"
        configFile rootProject.file('checkstyle/checkstyle.xml')
    }

    ext {
        daggerVersion = '2.55'
        picocliVersion = '4.7.6'
        lombokVersion = '1.18.36'
        gsonVersion = '2.12.1'
        junitBomVersion = '5.10.0'
    }

    dependencies {
        compileOnly "org.projectlombok:lombok:${lombokVersion}"
        annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

        implementation "com.google.dagger:dagger:${daggerVersion}"
        annotationProcessor "com.google.dagger:dagger-compiler:${daggerVersion}"

        implementation("com.google.code.gson:gson:${gsonVersion}")

        implementation "org.slf4j:slf4j-api:1.7.36"
        implementation "org.slf4j:slf4j-simple:1.7.36"

        testImplementation platform("org.junit:junit-bom:${junitBomVersion}")
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }

    test {
        useJUnitPlatform()
    }
}

dependencies {
    implementation project(':ddns-client')
    implementation project(':ddns-web-api')

    implementation 'com.sun.mail:jakarta.mail:2.0.1'

    implementation "info.picocli:picocli:${picocliVersion}"
    annotationProcessor "info.picocli:picocli-codegen:${picocliVersion}"

    implementation("commons-codec:commons-codec:1.18.0")
}
