plugins {
    id 'java'
}

group = 'ddns.connector'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    httpcomponentsVersion = '5.3.3'
}

dependencies {
    implementation project(':ddns-client')

    implementation "org.apache.httpcomponents.core5:httpcore5:${httpcomponentsVersion}"

    testImplementation platform("org.junit:junit-bom:${junitBomVersion}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
}
