plugins {
    id 'java'
}

group = 'ddns.webapi'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    httpcomponentsCoreVersion = '5.3.4'
}

dependencies {
    implementation project(':ddns-client')

    implementation "org.apache.httpcomponents.core5:httpcore5:${httpcomponentsCoreVersion}"
}
